# Status
set -g status "on"
set -g status-bg black
set -g status-justify "right"
set -g status-left-length "100"
set -g status-right-length "100"

# Prompt to display when tmux prefix key is pressed
set -g @mode_indicator_prefix_prompt " WAIT "
set -g @mode_indicator_copy_prompt " COPY "
set -g @mode_indicator_sync_prompt " SYNC "
set -g @mode_indicator_empty_prompt " NORM "

set -g @mode_indicator_copy_mode_style 'bg=yellow,fg=black,bold'
set -g @mode_indicator_sync_mode_style 'bg=red,fg=black,bold'
set -g @mode_indicator_empty_mode_style 'bg=cyan,fg=black,bold'

# style values for empty prompt
set -g message-style "fg=white,bg=black,align=centre"
set -g message-command-style "fg=white,bg=brightblack,align=centre"

# Panes
set -g pane-border-style fg=brightblack
set -g pane-active-border-style fg=magenta

# Windows
setw -g window-status-activity-style fg=white,bg=black,none
setw -g window-status-separator ""
setw -g window-status-style fg=white,bg=black,none

# Statusline
set -g status-left "#{tmux_mode_indicator}" # Keeps the mode indicator on the far left

set -g status-right ""                      # Removed the clock entirely

# Window-status
setw -g window-status-format "#[bg=black,fg=brightblack]  #W "
setw -g window-status-current-format "#[bg=cyan,fg=black] * #W "

# Modes
setw -g clock-mode-colour blue
setw -g mode-style fg=yellow,bg=white,bold
