XDG_CONFIG_HOME=$HOME/.config
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state
XDG_CACHE_HOME=$HOME/.cache
CARGO_HOME=$HOME/.local/share/cargo
FZF_DEFAULT_OPTS_FILE=$HOME/.config/fzf/fzf-opts
GOMODCACHE=$HOME/.cache/go/mod
GOPATH=$HOME/.local/share/go
GTK2_RC_FILES=$HOME/.config/gtk-2.0/gtkrc
INPUTRC=$HOME/.config/shell/inputrc
NPM_CONFIG_CACHE=$HOME/.cache/npm
NPM_CONFIG_INIT_MODULE=$HOME/.config/npm/config/npm-init.js
NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm
PASSWORD_STORE_DIR=$HOME/.local/share/password-store
RUSTUP_HOME=$HOME/.local/share/rustup
SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
WGETRC=$HOME/.config/wget/wgetrc
WINEPREFIX=$HOME/.local/share/wineprefixes/default
