# Minimal setup for Riverwm
# WIP because I only have desktop PC atm so I can't test how modules like battery and wifi look like

#-----------------------------------------------------#
#                      Bar Settings                   #
#-----------------------------------------------------#

bg-1: &bg-1 100F0Fff # Background
bg-2: &bg-2 1C1B1Aff # Background 2
bg-3: &bg-3 282726ff # Background 3
fg-1: &fg-1 CECDC3ff # Text 1
fg-2: &fg-2 B7B5ACff # Text 2
purple: &purple A02F6Fff # Purple
cyan: &cyan 24837Bff # Cyan
symbol: &symbol Symbols Nerd Font Mono:pixelsize=14

bar:
  height: 26 # Height without border
  location: top
  background: *bg-1
  foreground: *fg-1
  font: JetBrains Mono:pixelsize=14
  spacing: 6
  margin: 10
  border:
    width: 2 # This increases the overall height
    color: *bg-1

  #-----------------------------------------------------#
  #                     Modules Center                  #
  #-----------------------------------------------------#

  center:
    - clock:
        date-format: "%b, %d"
        time-format: "%H:%M"
        content:
          - string: { margin: 8, text: "{date}" }
          - string: { text: "{time}" }

  #-----------------------------------------------------#
  #                      Modules  Left                  #
  #-----------------------------------------------------#

  left:
    - river:
        anchors:
          - base: &river_base
              margin: 10
              default: { string: { text } }
              conditions:
                id == 1: { string: { text: 1 } }
                id == 2: { string: { text: 2 } }
                id == 3: { string: { text: 3 } }
                id == 4: { string: { text: 4 } }
                id == 5: { string: { text: 5 } }
                id == 6: { string: { text: 6 } }
                id == 7: { string: { text: 7 } }
                id == 8: { string: { text: 8 } }
                id == 9: { string: { text: 9 } }
        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  foreground: *purple
                  deco: { border: { size: 1, color: *bg-2 } }
              state == focused:
                map:
                  <<: *river_base
                  foreground: *cyan
                  deco: { border: { size: 1, color: *bg-3 } }
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: { empty: {} }
              state == invisible && occupied:
                map:
                  <<: *river_base
    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: { empty: {} }
              activated:
                - string:
                    { left-margin: 5, text: "{app-id}", foreground: *cyan }
                - string: { text: ": {title}", max: 70, foreground: *fg-2 }

  #-----------------------------------------------------#
  #                      Modules Right                  #
  #-----------------------------------------------------#

  right:
    - script:
        path: ~/.config/yambar/scripts/caffeine.sh
        poll-interval: 5000
        args: []
        content:
          string:
            margin: 5
            text: "{icon}"
            font: *symbol
            on-click: "~/.config/yambar/scripts/caffeine.sh toggle"
    - network:
        content:
          map:
            on-click:
              left: "networkmanager_dmenu"
              right: "foot -a floatterm -e nethogs"
            conditions:
              name == enp7s0:
                map:
                  default:
                    - string: { text: 󰅛, font: *symbol }
                  conditions:
                    state == up:
                      - string: { text: 󰱓, font: *symbol }
                    state == down:
                      - string: { text: 󰅛, font: *symbol }
    ## WIP need to test how this works when I have wifi
    #    - network:
    #        content:
    #          map:
    #            conditions:
    #              name == wlp3s0:
    #                map:
    #                  default:
    #                    - string: { text: , font: *symbol }
    #                  conditions:
    #                    state == up:
    #                      - string: { text: , font: *symbol }
    #                    state == down:
    #                      - string: { text: , font: *symbol }
    #                    state == unknown:
    #                      - string: { text: , font: *symbol }
    ##
    - label:
        content:
          {
            string:
              {
                text: "󰐥",
                font: *symbol,
                left-margin: 10,
                on-click: sh -c "bemenu_power",
              },
          }
