[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

[default_session]
command = "niri --config /etc/greetd/niri-greeter.kdl"
user = "greeter"

# Auto start if you wish
# [initial_session]
# command = "niri-session"
# user = "bazz"
