[terminal]

# TTY
vt = 7

# Default greeter
[default_session]
command = "tuigreet -t -r -c sway-start --asterisks --power-shutdown 'doas poweroff' --power-reboot 'doas reboot'"
user = "_greeter"

# Autologin
#[initial_session]
#command = "sway-start"
#user = "bazz"
