[terminal]
vt = 1

# Tuigreet
[default_session]
command = "tuigreet -t -r --remember-session  --asterisks --power-shutdown 'systemctl poweroff' --power-reboot 'systemctl reboot' -s /etc/greetd/sessions/:/usr/share/wayland-sessions/"
user = "greeter"

# Auto login
#[initial_session]
#command = "Hyprland"
#user = "bazz"
