# CUSTOM NOTIFICATION RULES AND OVERRIDES

[app-name=Audio-notify]
history=0

[app-name=btnot]
history=0

[app-name=gpu-screen-recorder]
history=0
text-alignment=center

[app-name=Media-notify]
text-alignment=center
history=0

[app-name=niri]
history=0
text-alignment=center

[app-name=swayidle]
history=0
text-alignment=center
width=150

[app-name=thunar]
history=0

[app-name=time-noti]
font=Adwaita Sans 11
history=0
text-alignment=center
width=180

[app-name=vol-osd grouped=false]
invisible=0

[app-name=vol-osd]
history=0
padding=10
text-alignment=center
width=200

[app-name=wl-color-picker]
history=0
text-alignment=center
width=250

[app-name=wl-freeze]
history=0
text-alignment=center

[app-name=wl-shot]
history=0
text-alignment=center
width=380

[mode=dnd]
invisible=1
