# CUSTOM NOTIFICATION RULES AND OVERRIDES

# Vol-OSD
[app-name=vol-osd]
border-size=1
history=0
padding=10
border-color=#403E3C
text-alignment=center
width=200

# Audio notify
[app-name=Audio-notify]
history=0

# Media notify
[app-name=Media-notify]
text-alignment=center
history=0

# Screen Recorder
[app-name=gpu-screen-recorder]
history=0
text-alignment=center

# Wl-shot
[app-name=wl-shot]
history=0
text-alignment=center
width=380

# Clock
[app-name=time-noti]
border-color=#a02f6f
font=Adwaita Sans 11
history=0
text-alignment=center
width=125

# Do not disturb
[mode=dnd]
invisible=1

# Show Vol-OSD even with DND
[app-name=vol-osd grouped=false]
invisible=0
