# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# RESTART IGNIS AFTER CHANGIN THESE
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# ══════════════════════════════════════════════════════════════
# WEATHER
# ══════════════════════════════════════════════════════════════
[weather]
api_key = ""                       # or OPEN_WEATHER_APIKEY
city_id = ""                       # or OPEN_WEATHER_CITY_ID
cache_ttl = 600
use_12h_format = false

# ══════════════════════════════════════════════════════════════
# UI · MONITORS
# ══════════════════════════════════════════════════════════════
[ui.monitors]
primary = 0
bar = 0
osd = 0
notifications = 0
recording_overlay = 0
weather = 0
power_overlay = 0
system_menu = 0
notification_center = 0

# ══════════════════════════════════════════════════════════════
# OSD · TIMEOUTS (milliseconds)
# ══════════════════════════════════════════════════════════════
[ui.timeouts]
osd = 2000
volume_osd = 2000
time_osd = 5000
workspace_osd = 1500

# ══════════════════════════════════════════════════════════════
# UI · BAR
# ══════════════════════════════════════════════════════════════
[ui.bar]
# Clock format
clock_format = "%H:%M"
clock_interval = 60000  # Poll interval in milliseconds. Edit this to 1000 if you use seconds in format
# Icon size
icon_size = 16
# Tray icon size
tray_icon_size = 20
# Remember bar state after re-start
remember_state = true
# Enable/disable system tray
show_system_tray = true

# Apps that show window title instead of app class
window_title_exceptions = [
  "firefox",
  "zen",
  "mpv"
]
# Workspace labels
[workspaces]
#labels = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
#labels = ["一", "二", "三", "四", "五", "六", "七", "八", "九", "十"]
labels = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X"]

# ══════════════════════════════════════════════════════════════
# UI · NOTIFICATIONS
# ══════════════════════════════════════════════════════════════
[ui.notifications]
max_history = 10
popup_timeout = 5000 # Milliseconds

#  Hide useless stuff from history (My personal preference, you probably wan't to remove these)
filter_keywords = [
  "Audio notify",
  "Hypridle",
  "Hyprland",
  "Idle timer",
  "Smart-gaps",
  "TMUX",
  "Clock is",
  "Playerctl",
]

# ══════════════════════════════════════════════════════════════
# RECORDER
# ══════════════════════════════════════════════════════════════
[recorder]
audio_device = "default_output"
video_format = "mp4"

# ══════════════════════════════════════════════════════════════
# BATTERY
# ══════════════════════════════════════════════════════════════
[battery]
critical_threshold = 15
warning_threshold = 30

# ══════════════════════════════════════════════════════════════
# ANIMATIONS
# ══════════════════════════════════════════════════════════════
[animations]
revealer_duration = 200

# ══════════════════════════════════════════════════════════════
# PATHS
# ══════════════════════════════════════════════════════════════
[paths]
recordings_dir = "~/Videos/Captures"
screenshots_dir = "~/Pictures/Screenshots"
