# Settings
background_alpha=0.4
engine_short_names=1
font_file=/usr/share/fonts/Adwaita/AdwaitaSans-Regular.ttf
font_size=20
horizontal=1
hud_no_margin=1
legacy_layout=0
no_small_font=1

# Order
cpu_stats
ram
cpu_temp
gpu_stats
vram
gpu_temp
fps
time
time_format=%H:%M

# Toggle bind
toggle_hud=Shift_R+F12

# Colors
cpu_color=24837b
engine_color=af3029
gpu_color=66800b
horizontal_separator_color=878580
io_color=A491D3
ram_color=24837b
vram_color=66800b
