#!/bin/sh

## Load essentials
if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
        [ -x "${f}" ] && source "${f}"
    done && unset f
fi

## Autostart

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
# setxkbmap fi & 
setbg &
~/.config/Screenlayout/monitor.sh &
locker-toggler -e &
picom -b

processes=( "dwmblocks" "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1" "clipmenud" )
for process in "${processes[@]}"; do
    if ! pgrep -x "$process" > /dev/null; then
        "$process" &
    fi
done

[ -n "$xrdbpid" ] && wait "$xrdbpid"

exec dwm
