#!/bin/sh

# [[ -f ~/.zshenv ]] && source ~/.zshenv
[[ -f ~/.zprofile ]] && source ~/.zprofile  # This is only needed with lightdm to source .zsenv or .zprofile https://wiki.archlinux.org/title/LightDM#Optional_configuration_and_tweaks

xrdb -merge "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"
