# Default values https://codeberg.org/dnkl/fuzzel/src/branch/master/fuzzel.ini

# colors
include=~/.cache/wal/colors-fuzzel.ini

# settings
font=Adwaita Mono:size=13, Symbols Nerd Font Mono:size=13
dpi-aware=yes
prompt="󰍉  "
placeholder="Type"
password-character=*
show-actions=no
terminal=foot
exit-on-keyboard-focus-loss=no
layer=overlay
icon-theme=Papirus-Dark
icons-enabled=yes
image-size-ratio=0.2

# style
lines=8
width=30
tabs=8
horizontal-pad=40
vertical-pad=20
inner-pad=10

[border]
width=1
radius=4
