#!/usr/bin/env bash

# rofi theme
THEME="$HOME/.config/rofi/rofi_screenrecord/theme.rasi"

get_options() {
  echo "  Record Screen (MP4)"
  echo "  Record Region (MP4+audio)"
  echo "  Record Region (MP4)"
  echo "  Stop Recording"
}

main() {

  # Get choice from rofi
  choice=$( (get_options) | rofi -dmenu -i -fuzzy -p "Capture" -theme "$THEME")

  # If user has not picked anything, exit
  if [[ -z "${choice// /}" ]]; then
    exit 1
  fi

  # run the selected command
  case $choice in
  '  Record Screen (MP4)')
    quick-record -v
    ;;
  '  Record Screen (MP4+Audio)')
    quick-record -sc
    ;;
   '  Record Region (MP4)')
    quick-record -r
    ;;
  '  Stop Recording')
    quick-record -kill
    ;;
  esac

  # done
  set -e
}

main &

exit 0
