#!/bin/sh
while read file
do
    case "$1" in
        "d")
            mv "$file" ~/.trash ;;
        "r")
            convert -rotate 90 "$file" "$file" ;;
        "c")
            echo -n "$file" | xclip -selection clipboard ;;
        "w")
            feh --bg-scale "$file" ;;
        "l")
            betterlockscreen -q -u "$file"
            notify-send "Locksreen Wallpaper Changed!" ;;
        "a")
            feh --bg-scale "$file" &&  betterlockscreen -q -u "$file" 
            notify-send  "Locksreen Wallpaper Changed!" ;;
        "y")
            xclip -selection clipboard "$file" -t image/png &&
                notify-send "$file copied to clipboard!"
        esac
    done
