# Settings
encryption_passcommand: sh -c "cat ~/Documents/credentials/.borg-passphrase"

# List of source directories to backup.
source_directories:
  - /home

# Paths of local or remote repositories to backup to.
repositories:
  - path: /mnt/nv1tb/Backup/borg
    label: local

# Retention policy for how many backups to keep.
keep_daily: 7
keep_weekly: 4
keep_monthly: 6

# Exludes
exclude_if_present:
  - .nobackup
  - .NOBACKUP
exclude_patterns:
  - "*.pyc"
  - "*/.vim*.tmp"
  - "- [Cc]ache"
  - "- [Tt]rash"
  - /etc/audit/audit
  - /etc/credstore
  - /etc/credstore.encrypted
  - /etc/gshadow
  - /etc/gshadow-
  - /etc/libaudit.conf
  - /etc/libvirt
  - /etc/pacman.d
  - /etc/qemu
  - /etc/ssl
  - /home/*/.cache
  - /home/*/.dbus
  - /home/*/.grsync
  - /home/*/.lesshst
  - /home/*/.local/share/Steam
  - /home/*/.local/share/Trash
  - /home/*/.local/share/libvirt
  - /home/*/.npm
  - /home/*/.nv
  - /home/*/.nvidia-settings-rc
  - /home/*/.pki
  - /home/*/.playonlinux
  - /home/*/.ssr
  - /home/*/.steam
  - /home/*/.steampath
  - /home/*/.steampid
  - /home/*/.themes
  - /home/*/.var
  - /home/*/.wget-hsts
  - /home/*/.wine
  - /home/*/Applications
  - /home/*/Desktop
  - /home/*/Downloads
  - /home/*/Music
  - /home/*/Pictures
  - /home/*/Public
  - /home/*/Sync
  - /home/*/Videos
  - /home/*/applications
  - /home/*/baloo
  - /home/*/dropbox
  - /home/*/gdrive
  - /home/*/icons
  - /home/*/onedrive
  - /home/*/public
  - /home/*/recentdocuments
  - /home/*/steam*
  - /home/*/temp
  - /home/*/trash
  - /home/*/vortex

exclude_caches: true
