## Don't print a new line at the start of the prompt
add_newline = false

## Make prompt a single line instead of two lines
[line_break]
disabled = true

## Prompt, directory etc
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Directory settings. This is almost stock
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold blue"
read_only = " "
truncation_length = 8
truncation_symbol = "…/"


## User
# [username]
# style_user = "green bold"
# style_root = "red bold"
# format = "[$user]($style) "
# disabled = false
# show_always = true

### Disable the package module, hiding it from the prompt completely. Add more or delete as you like
[package]
disabled = true

#[lua]
#disabled = false

#[python]
#disabled = true

#[ruby]
#disabled = true

#[rust]
#disabled = true

#[nodejs]
#disabled = true

#[java]
#disabled = true

#[golang]
#disabled = true

#[aws]
#disabled = true
