add_newline = false
format = """
$os\
$directory\
$git_branch\
$git_status\
$character\
$cmd_duration"""

right_format = "$time"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[directory]
format = "[$path]($style)(bold blue)[$read_only](bold red)($read_only_style) "
truncation_length = 3
truncation_symbol = '…/'
home_symbol = " ~"
read_only = " "

[time]
format = "[$time]($style)"
disabled = false
style = "grey"

[os]
disabled = false

[os.symbols]
Android = " "
Arch = " "
CentOS = " "
Debian = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
HardenedBSD = "ﲊ "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NetBSD = " "
NixOS = " "
openSUSE = " "
Pop = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
SUSE = " "
Ubuntu = " "
Unknown = " "

[git_branch]
style = "bold #7C83FD"

[git_metrics]
disabled = false

[git_status]
ahead = " ⇡ ${count}"
diverged = "⇕ ⇡ ${ahead_count} ⇣ ${behind_count}"
behind = "⇣ ${count}"
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#ff00dd"

[cmd_duration]
disabled = false
format = "[$duration]($style) "
style = "yellow"
#[sudo]
#disabled = false

