#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

############
# monitor(s)
############
#
bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
#bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9

# To make mouse movement smoother with higher refresh rate monitors
bspc config pointer_motion_interval 7ms

bspc config border_width          2
bspc config window_gap           10
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr &

###############
# Spiral scheme
###############
#bspc config automatic_scheme    spiral

# Set screen idle timeout (seconds)
xset s 3600 dpms 3600 3600 3600

##############
# Window rules
##############
#bspc rule -a Screenkey manage=off
bspc rule -a authy state=floating
bspc rule -a Joplin desktop='^4'
bspc rule -a Steam desktop='^6' state=floating= follow=off focus=off
bspc rule -a Pavucontrol state=floating
bspc rule -a Galculator state=floating
bspc rule -a mpv state=floating
bspc rule -a thunderbird desktop='^4' follow=on focus=on
bspc rule -a nitrogen state=floating
bspc rule -a Gimp-2.10 state=floating follow=off focus=off
bspc rule -a firefox desktop='^2' follow=on focus=on
bspc rule -a Gcolor3 state=floating
bspc rule -a ProtonUp-Qt state=floating follow=off focus=off
bspc rule -a feh state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a corectrl desktop '^7'
bspc rule -a qBittorrent desktop '^7'
bspc rule -a Nsxiv state=floating

########
# colors
########

bspc config focused_border_color        "#8EC07C"
bspc config normal_border_color         "#a89984"
bspc config active_border_color         "#a89984"
bspc config presel_feedback_color       "#5e81ac"

###########
# Autostart
###########

killall -9 picom corectrl /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

sleep 3 && picom &
sleep 2 && nitrogen --restore &
sh ~/.config/.screenlayout/monitor.sh &
sh ~/.config/bspwm/scripts/launch.sh &
nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
corectrl &
