[colors]

;; main colors
background      = #171B20
foreground      = #b6beca
subtext         = #e3e6eb

mantle          = #1a1e24
crust           = #1f2329


black           = #1c252c
red             = #e05f65
green           = #78dba9
yellow          = #f1cf8a
blue            = #70a5eb
magenta         = #c68aee
cyan            = #74bee9
white           = #dee1e6
peach           = #e9a180

black2          = #384148
red2            = #fc7b81
green2          = #94f7c5
yellow2         = #ffeba6
blue2           = #8cc1ff
magenta2        = #e2a6ff
cyan2           = #90daff
white2          = #fafdff 




