[colors]

;; main colors
background  = #282c34
foreground  = #bbc2cf

black       = #1c1f24
blue        = #51afef
cyan        = #5699af
green       = #98be65
magenta     = #c678dd
red         = #ff6c6b
white       = #dfdfdf
yellow      = #da8548

black2      = #5b6268
blue2       = #3071db
cyan2       = #46D9FF
green2      = #4db5bd
magenta2    = #a9a1e1
red2        = #ff6655
yellow2     = #ECBE7B


