[colors]

;; main colors
background      = #242730
foreground      = #bbc2cf
black           = #2a2e38
red             = #ff665c
green           = #7bc275
yellow          = #fcce7b
blue            = #51afef
magenta         = #C57BDB
cyan            = #5cEfFF
white           = #DFDFDF

black2          = #484854
red2            = #ff665c
green2          = #99bb66
yellow2         = #ecbe7b
blue2           = #51afef
magenta2        = #c678dd
cyan2           = #46D9FF
white2          = #bbc2cf
