[colors]

;; main colors
background      = #21222c
foreground      = #f8f8f2
black           = #21222c
red             = #ff5555
green           = #50fa7b
yellow          = #f1fa8c
blue            = #bd93f9
magenta         = #ff79c6
cyan            = #8be9fd
white           = #f8f8f2

black2          = #6272a4
red2            = #ff6e6e
green2          = #69ff94
yellow2         = #ffffa5
blue2           = #d6acff
magenta2        = #ff92df
cyan2           = #a4ffff
white2          = #ffffff 



