[module/arch-updates]
type = custom/script
exec = ~/.config/polybar/scripts/arch-updates.sh
interval = 3600
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-prefix = " "
format-prefix-foreground = ${colors.purple}
label = %output%
label-font = 2
format-prefix-font = 2
click-left = st -e $SHELL -c 'paru'

[module/cpu]
;https://github.com/jaagr/polybar/wiki/Module:-cpu
type = internal/cpu
interval = 2
format = <label>
format-background = ${colors.background}
format-foreground = ${colors.foreground}
format-prefix = " "
format-prefix-foreground = ${colors.red}
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.green}
label = %gb_used%
label-foreground = ${colors.foreground}

;[module/wlan]
;inherit = network-base
;interface-type = wireless
;label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/pulseaudio]
type = internal/pulseaudio
interval = 5
click-right = pgrep pavucontrol && killall pavucontrol || pavucontrol
format-volume = <label-volume>
format-volume-prefix = "󰕾 "
format-volume-prefix-foreground = ${colors.blue}
label-muted = shhh!
label-muted-foreground = ${colors.blue}
label-volume = %percentage%%
label-volume-foreground = ${colors.foreground}

[module/uptime]
;https://github.com/jaagr/polybar/wiki/User-contributed-modules#uptime
type = custom/script
exec = uptime | awk -F, '{sub(".*up ",x,$1);print $1}'
interval = 3600
label = %output%
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = "  "
format-prefix-foreground = ${colors.red}
label-font = 2

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/date]
type = custom/script
interval = 30
;label-font = 2
exec = date +"%H:%M"
label = %output%
format-prefix = " "
format-prefix-foreground = ${colors.yellow}
label-foreground = ${colors.foreground}
label-font = 2
click-left = ~/.config/polybar/scripts/calendar curr
scroll-up = ~/.config/polybar/scripts/calendar prev
scroll-down = ~/.config/polybar/scripts/calendar next

[module/playerctl]
type = custom/script
tail = true
interval = 3
format =  <label>
exec = playerctl metadata --format "{{ artist }} - {{ title }}"
exec-if = playerctl metadata -f {{playerName}} 2>/dev/null
format-font=4

[module/mpd]
type = internal/mpd
host = 127.0.0.1
port = 6600
interval = 2
label-song =  %artist% - %title%
label-offline = 

[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = true
enable-scroll = true
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;10
ws-icon-default = ♟

format = <label-state> <label-mode>

label-mode = %mode%
label-mode-padding = 1
label-mode-foreground = ${colors.background}
label-mode-background = ${colors.red}

label-focused = %index%
label-focused-foreground = ${colors.background}
label-focused-background = ${colors.purple}
label-focused-padding = 2

label-unfocused = %index%
label-unfocused-padding = 2

label-visible = %index%
label-visible-padding = 2

label-urgent = %index%
label-urgent-foreground = ${colors.background}
label-urgent-background = ${colors.red}
label-urgent-padding = 2

[module/bspwm]
type = internal/bspwm

enable-click = true
enable-scroll = true
reverse-scroll = false
pin-workspaces = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-default = " "

format = <label-state> <label-mode>

label-focused = %name%
label-focused-foreground = ${colors.background}
label-focused-background = ${colors.foreground}
label-focused-padding = 1
label-focused-font = 1

label-occupied = %name%
label-occupied-foreground = ${colors.foreground}
label-occupied-background = ${colors.background}
label-occupied-padding = 1
label-occupied-font = 1

label-urgent = %name%
label-urgent-foreground = #282828
label-urgent-background = ${colors.red}
label-urgent-padding = 1
label-urgent-font = 1

label-empty = %name%
label-empty-foreground = #a89984
label-empty-background = ${colors.background}
label-empty-padding = 1
label-empty-font = 1

label-locked = "  "
label-locked-foreground = ${colors.foreground}
label-sticky = "  "
label-sticky-foreground = ${colors.foreground}
label-private =  "     "
label-private-foreground = ${colors.foreground}
