font: Adwaita Mono 13
background: "#100F0F"
color: "#CECDC3"
border: "#1C1B1A"
separator: " ➜ "
border_width: 1
corner_r: 4
padding: 20
rows_per_column: 2
column_padding: 25

anchor: top
margin_right: 16
margin_bottom: 16
margin_left: 16
margin_top: 16

inhibit_compositor_keyboard_shortcuts: true
auto_kbd_layout: true

menu:
  - key: "b"
    desc: bash
    cmd: foot -e nvim ~/.bashrc ~/.config/shell/aliases ~/.config/shell/inputrc
  - key: "d"
    desc: fuzzel
    cmd: foot -e nvim ~/.config/fuzzel/fuzzel.ini
  - key: "f"
    desc: foot
    cmd: foot -e nvim ~/.config/foot/foot.ini
  - key: "v"
    desc: neovim
    cmd: foot sh -c "cd ~/.config/nvim && vopen ."
  - key: "n"
    desc: niri
    cmd: foot -e nvim  ~/.config/niri/*
  - key: "w"
    desc: waybar
    cmd: foot sh -c "cd ~/.config/waybar/ && nvim *"
  - key: "k"
    desc: wlr-which-key
    cmd: foot sh -c "cd ~/.config/wlr-which-key// && nvim *"
  - key: "m"
    desc: System Monitor
    submenu:
      - key: "a"
        desc: Atop
        cmd: foot -T atop -e amdgpu_top --smi
      - key: "b"
        desc: Btop
        cmd: foot -a btop -e btop
      - key: "l"
        desc: Logs
        cmd: foot -a foot -T journalctl -e journalctl -f
      - key: "c"
        desc: Combined [ tmux-window ]
        cmd: foot -a Sysmon -T Sysmon -e ~/.local/bin/tmux-sysmon.sh
