font: Adwaita Mono 13
background: "#101010"
color: "#CCCCCC"
border: "#1C1C1C"
separator: " ➜ "
border_width: 1
corner_r: 4
padding: 20
rows_per_column: 3
column_padding: 25

anchor: top
margin_right: 16
margin_bottom: 16
margin_left: 16
margin_top: 16

inhibit_compositor_keyboard_shortcuts: true
auto_kbd_layout: true

menu:
  - key: "b"
    desc: Bash
    cmd: foot -e nvim ~/.bashrc ~/.config/shell/aliases ~/.config/shell/inputrc
  - key: "d"
    desc: Fuzzel
    cmd: foot -e nvim ~/.config/fuzzel/fuzzel.ini
  - key: "f"
    desc: Foot
    cmd: foot -e nvim ~/.config/foot/foot.ini
  - key: "k"
    desc: Wlr-which-key
    cmd: foot sh -c "cd ~/.config/wlr-which-key/ && nvim *"
  - key: "n"
    desc: Niri
    cmd: foot sh -c "cd ~/.config/niri/ && vopen ."
  - key: "p"
    desc: "Pywal"
    cmd: foot -e nvim ~/.local/bin/setbg  ~/.config/wal/templates/*
  - key: "v"
    desc: Nvim
    cmd: foot sh -c "cd ~/.config/nvim && vopen ."
  - key: "w"
    desc: Waybar
    cmd: foot sh -c "cd ~/.config/waybar/ && vopen ."
  - key: "m"
    desc: Monitor
    submenu:
      - key: "a"
        desc: Atop
        cmd: foot -T atop -e amdgpu_top --smi
      - key: "b"
        desc: Btop
        cmd: foot -a btop -e btop
      - key: "l"
        desc: Logs
        cmd: foot -a foot -T journalctl -e journalctl -f
      - key: "c"
        desc: Combined [ tmux-window ]
        cmd: foot -a Sysmon -T Sysmon -e ~/.local/bin/tmux-sysmon.sh
