font: Adwaita Sans 13
background: "#100F0F"
color: "#CECDC3"
border: "#282726"
separator: " ➜ "
border_width: 1
corner_r: 4
padding: 20
column_padding: 25

anchor: top
margin_right: 8
margin_bottom: 8
margin_left: 8
margin_top: 8

inhibit_compositor_keyboard_shortcuts: true
auto_kbd_layout: true

menu:
  - key: "d"
    desc: Fuzzel
    cmd: foot -e nvim ~/.config/fuzzel/fuzzel.ini
  - key: "f"
    desc: Foot
    cmd: foot -e nvim ~/.config/foot/foot.ini
  - key: "i"
    desc: Ignis
    cmd: foot sh -c "cd ~/.config/ignis && vopen ."
  - key: "v"
    desc: Neovim
    cmd: foot sh -c "cd ~/.config/nvim && vopen ."
  - key: "n"
    desc: Niri
    cmd: foot -e nvim  ~/.config/niri/*
  - key: "m"
    desc: System Monitor
    submenu:
      - key: "a"
        desc: Atop
        cmd: foot -T atop -e amdgpu_top --smi
      - key: "b"
        desc: Btop
        cmd: foot -a btop -e btop
      - key: "l"
        desc: Logs
        cmd: foot -a foot -T journalctl -e journalctl -f
      - key: "c"
        desc: Combined [ tmux-window ]
        cmd: foot -a Sysmon -T Sysmon -e ~/.local/bin/tmux-sysmon.sh
