#!/usr/bin/env bash

HISTFILE="${XDG_CACHE_HOME:-$HOME/.cache}/web-search-history"

mkdir -p "$(dirname "$HISTFILE")"
touch "$HISTFILE"

query=$(
  head -50 "$HISTFILE" |
    fuzzel -d --minimal-lines \
      --line-heigh 26
)
exit_code=$?

# Alt+0 → clear history
if [ "$exit_code" -eq 19 ]; then
  confirmation=$(
    printf "No\nYes\n" |
      fuzzel -d \
        --placeholder "Delete search history?" \
        --minimal-lines
  )

  if [ "$confirmation" = "Yes" ]; then
    rm -f "$HISTFILE"
  fi

  exit 0
fi

[ -z "$query" ] && exit 0

{
  printf '%s\n' "$query"
  grep -Fvx -- "$query" "$HISTFILE" 2>/dev/null
} | head -50 >"${HISTFILE}.tmp"

mv "${HISTFILE}.tmp" "$HISTFILE"

case "$query" in
"!y "*)
  q="${query#!y }"
  url="https://www.youtube.com/results?search_query=${q// /+}"
  ;;
"!a "*)
  q="${query#!a }"
  url="https://wiki.archlinux.org/title/Special:Search?search=${q// /+}"
  ;;
"!w "*)
  q="${query#!w }"
  url="https://en.wikipedia.org/wiki/Special:Search?search=${q// /+}"
  ;;
*)
  url="https://www.google.com/search?q=${query// /+}"
  ;;
esac

xdg-open "$url" >/dev/null 2>&1 &
